# Generated by Django 4.0.2 on 2022-04-11 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ohq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(default='ongoing', max_length=200),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(default='public', max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
